### ISSUE TITLE
greetings form the neighbors

### ISSUE THREAD

**Issue by codingjoe** [pybee/beefore#21]
Hi there, long time no see!

a college just send the link for this project. Looks great. So great in fact, that me and a bunch of friends have been working on something similar. Maybe we can join forces?

I did present it on DjangoConEU2018, but I think @freakboy3742 was making too many bee jokes to notice what I was talking about ;)

Anyhow, there are some differences on how we implemented this concept. We did use AWS lambda to run all linters. We also used GitHubs new checks API. This allows users to stay on GitHub and receive feedback immediately.

Maybe it doesn't make sense to combine those to project after all, in any case we made it open source. Feel free to borrow code if you need it :)

https://lambdalint.github.io
https://github.com/lambdalint

Best
-Joe

**Comment by freakboy3742** [comment]
Howdy, neighbour!

I'm always up for combining efforts, but in this case, I'm not sure what that would look like. Beefore is part of a larger piece of CI tooling (BeeKeeper) that uses ECS and Docker, rather than Lambda; our integration with Github's Check API is at that level. But if there's a way to share code in a meaningful way, I'm all for it.

**Comment by codingjoe** [comment]
Howdy RusselI,

Thanks for responding so quickly. I see, the approaches are somewhat different.
Anyways, I'll keep this project on my radar. Should we ever develop something that might help here too, I will drop a message.

Best
-Joe
