### ISSUE TITLE
Autoformat python code?

### ISSUE THREAD

**Issue by goanpeca** [pybee/beefore#7]
Are we using (or planing to use) some code formatter (yapf/autopep8) to format code, check code on PRs?

I wrote https://github.com/continuumio/ciocheck to do this on some of my projects, so that if CI fails if the code formatter changed the code in anyway.

**Comment by freakboy3742** [comment]
Beefore has a pycodestyle task; we're in the process of rolling this out across our repositories.

**Comment by goanpeca** [comment]
@freakboy3742 pycodestyle checks, but yapf or autopep8 re format (programmatically) code based on some configuration rules, so it is not exactly what I asked for.

The idea is not "waste time" reviewing code style that can be accomplished automatically by either one of the mentioned libraries.

**Comment by freakboy3742** [comment]
I'm wary of auto-reformatters - human legibility matters more than hard adherence to rules (which is the opening statement of PEP8). pycodestyle alerts developers when there's a problem; the beefore task adds comments on the PR telling contributors where the problem is; but there's always multiple ways to reformat code to be PEP8 compliant, including (occasionally) the `#noqa` marker.

**Comment by goanpeca** [comment]
Fair enough ;-)
